name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.12.2"
          cabal-version: "latest"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Update package list
        run: cabal update

      - name: Build with optimization
        run: cabal build --enable-optimization=2

      - name: Install to local bin
        run: cabal install --install-method=copy --installdir=./bin

      - name: Create release archive
        run: |
          mkdir -p release/blogroll
          cp bin/blogroll release/blogroll/
          cd release
          tar -czf blogroll.tar.gz blogroll/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/blogroll.tar.gz
          generate_release_notes: true

      - name: Upload artifact for daily job
        uses: actions/upload-artifact@v4
        with:
          name: blogroll-binary
          path: release/blogroll.tar.gz
          retention-days: 90
